import type { AnalysisResult, AnalysisSummary, Finding } from '../types';

export const finding = (overrides: Partial<Finding> = {}): Finding => ({
  id: 'f1',
  detector: 'content.urgency',
  category: 'content',
  severity: 'medium',
  confidence: 0.8,
  title: 'Urgency language',
  description: 'The message imposes deadlines.',
  whyItMatters: 'Pressure short-circuits checking.',
  evidence: [{ label: 'Phrase', value: '"within 24 hours"' }],
  recommendation: 'Slow down.',
  source: 'rule',
  method: 'Weighted phrase patterns.',
  scoreGroup: 'content',
  ...overrides,
});

const body = 'Your account will be suspended within 24 hours unless you verify your credentials.';

export const analysis = (overrides: Partial<AnalysisResult> = {}): AnalysisResult => ({
  id: 'an_test0000000001',
  createdAt: '2026-10-05T10:00:00.000Z',
  sourceName: 'test.eml',
  sizeBytes: 2048,
  sha256: 'a'.repeat(64),
  metadata: {
    from: {
      name: 'Microsoft Account Team',
      address: 'no-reply@micr0soft.com',
      domain: 'micr0soft.com',
    },
    to: [{ name: '', address: 'analyst@example.org', domain: 'example.org' }],
    cc: [],
    bcc: [],
    subject: 'Unusual sign-in activity',
    headers: [{ name: 'Subject', value: 'Unusual sign-in activity' }],
  },
  body: { text: body, textSource: 'plain', hasHtml: false, truncated: false },
  received: [],
  authentication: {
    spf: { state: 'fail', result: 'fail', detail: 'SPF failed' },
    dkim: { state: 'not_present', detail: 'No DKIM' },
    dmarc: { state: 'fail', result: 'fail', detail: 'DMARC failed' },
    headerCount: 1,
    dkimSignaturePresent: false,
  },
  urls: [],
  attachments: [],
  mimeStructure: [],
  findings: [
    finding({
      id: 'f1',
      spans: [
        {
          start: body.indexOf('within 24 hours'),
          end: body.indexOf('within 24 hours') + 15,
          text: 'within 24 hours',
        },
      ],
    }),
    finding({
      id: 'f2',
      detector: 'auth.dmarc',
      category: 'authentication',
      severity: 'critical',
      confidence: 0.95,
      title: 'DMARC failed for the From domain',
      scoreGroup: 'authentication',
    }),
    finding({
      id: 'f3',
      detector: 'header.return_path_mismatch',
      category: 'sender',
      severity: 'low',
      title: 'Return-Path differs',
      scoreGroup: 'sender',
    }),
  ],
  ml: {
    available: true,
    modelName: 'MailSherlock Phishing Classifier',
    modelVersion: '1.0.0',
    probability: 0.91,
    threshold: 0.55,
    label: 'phishing',
    confidence: 'high',
    signals: [],
  },
  threatIntel: [],
  risk: {
    score: 87,
    level: 'critical',
    classification: 'phishing',
    ruleScore: 80,
    rawPoints: 120,
    contributions: [{ label: 'Sender authentication', points: 40, kind: 'rule' }],
    trustedContext: false,
    summary: 'Critical risk - classified phishing.',
  },
  stages: [],
  parseWarnings: [],
  engineVersion: '1.0.0',
  ...overrides,
});

export const summary = (overrides: Partial<AnalysisSummary> = {}): AnalysisSummary => ({
  id: 'an_test0000000001',
  createdAt: '2026-10-05T10:00:00.000Z',
  sourceName: 'test.eml',
  sender: 'no-reply@micr0soft.com',
  senderDomain: 'micr0soft.com',
  subject: 'Unusual sign-in activity',
  riskScore: 87,
  riskLevel: 'critical',
  classification: 'phishing',
  findingCount: 3,
  criticalCount: 1,
  highCount: 0,
  mlProbability: 0.91,
  modelVersion: '1.0.0',
  feedback: null,
  ...overrides,
});
